# Generated by Django 5.1.6 on 2025-04-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('verbose_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('degrees', 'Degrees'), ('char', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('choice', 'Choice'), ('datetime', 'DateTime')], max_length=20)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_field_values', to='app.data')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datafield')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='field_values',
            field=models.ManyToManyField(related_name='data_field_values_reverse', to='app.datafieldvalue'),
        ),
    ]
