# Generated by Django 5.2 on 2025-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('degrees', 'Degrees'), ('char', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('choice', 'Choice'), ('time', 'Time')], max_length=20),
        ),
    ]
