# Generated by Django 5.1.6 on 2025-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_time', models.FloatField(default=-1.0)),
                ('tilt', models.FloatField(default=-1.0)),
                ('azimuth', models.FloatField(default=-1.0)),
                ('panel_qty', models.IntegerField(default=1)),
                ('sys_rating', models.FloatField(default=-1.0)),
                ('inv_manu', models.CharField(max_length=1000)),
                ('array_type', models.CharField(max_length=1000)),
                ('sqrl_screen', models.BooleanField(default=None, null=True)),
                ('cons_monito', models.BooleanField(default=None, null=True)),
                ('truss_rafter', models.CharField(max_length=10)),
                ('reinforcements', models.BooleanField(default=None, null=True)),
                ('elec_inspec', models.BooleanField(default=None, null=True)),
                ('intercon_type', models.CharField(max_length=1000)),
                ('module_len', models.FloatField(default=-1.0)),
                ('module_width', models.FloatField(default=-1.0)),
                ('module_weight', models.FloatField(default=-1.0)),
                ('array_num', models.FloatField(default=-1.0)),
                ('circuit_num', models.FloatField(default=-1.0)),
                ('reinforcement_num', models.FloatField(default=-1.0)),
                ('roof_type', models.CharField(max_length=200)),
                ('attach_type', models.CharField(max_length=200)),
                ('story_num', models.FloatField(default=-1.0)),
                ('season', models.CharField(max_length=200)),
                ('est_salary_empl', models.FloatField(default=-1.0)),
                ('est_salary_hr', models.FloatField(default=-1.0)),
                ('est_direct_time', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
