# Generated by Django 5.2 on 2025-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_datafield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafieldvalue',
            name='value',
            field=models.JSONField(blank=True),
        ),
    ]
