# Generated by Django 5.2 on 2025-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_datafieldvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafieldvalue',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
