# Generated by Django 5.2 on 2025-04-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_datafieldvalue_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Project',
        ),
    ]
